{{- if eq .Values.prometheus.podmonitor true -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kratos-operator.podmonitor
  namespace: {{ template "kratos-operator.namespace" . }}
  labels:
{{ include "kratos-operator.prometheusLabels" . | indent 4 }}
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: {{ .Values.prometheus.port }}
    path: {{ .Values.prometheus.path }}
    metricRelabelings: {}
    relabelings: {}
  namespaceSelector:
    matchNames:
      - {{ template "kratos-operator.namespace" . }}
  selector:
    matchLabels:
      app: {{ template "kratos-operator.name" . }}
{{ end }}
